[tool.poetry]
name = "arch-patterns"
version = "0.1.0"
description = "проект для изучения паттернов разработки Python по книге Г.Персиваля и Б.Грегори с использование FastAPI (тоже для изучения)"
authors = ["Evgeny Kungurov <eakungur@mts.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
python-multipart = "^0.0.6"
sqlalchemy = "^2.0.25"
dynaconf = "^3.2.4"
aiofiles = "^23.2.1"
passlib = "^1.7.4"
alembic = "^1.13.1"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
requests = "^2.31.0"
httpx = "^0.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
