"""[upd] accounts - added new columns

Revision ID: f33f8eaad87c
Revises: 2babe647e9ba
Create Date: 2024-01-23 09:46:34.274925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33f8eaad87c'
down_revision: Union[str, None] = '2babe647e9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'avatar')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###
