"""init

Revision ID: 45a0f9814fb7
Revises: 
Create Date: 2024-02-21 21:08:01.887545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '45a0f9814fb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'batches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reference', sa.String(length=255), nullable=True),
        sa.Column('sku', sa.String(length=255), nullable=True),
        sa.Column('eta', sa.Date(), nullable=True),
        sa.Column('_purchased_quantity', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'order_lines',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('sku', sa.String(length=255), nullable=True),
        sa.Column('qty', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'allocations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('order_line_id', sa.Integer(), nullable=True),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
        sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('order_lines')
    op.drop_table('batches')
    # ### end Alembic commands ###
